### ISSUE TITLE
A little question

### ISSUE THREAD

**Issue by AlwaysLightHeart** [chrsmrrs/k-gnn#4] opened 2019-07-04 12:29 UTC
I have installed torch_geometric 1.3.0 and Pytorch 1.1.0, however I can not import one_hot from torch_geometric.utils.  Could you tell me what's the version of your torch_geometric?

**Comment by rusty1s** [comment] 2019-07-04 12:35
Fixed in master. Sorry!

**Closed as completed** 2019-07-04 12:35 UTC

**Comment by AlwaysLightHeart** [comment] 2019-07-04 12:49
Thanks! That did it.

**Comment by AlwaysLightHeart** [comment] 2019-07-05 01:27
Execuse me，I didn't  run the file 1-2-3-proteins.py successfully.  I have tried some methods but can not solve this prolblem. The error information is as follows:
/home/bigdata/anaconda3/envs/ML/bin/python /home/bigdata/Downloads/pycharm-community-2018.3.2/helpers/pycharm/_jb_pytest_runner.py --path /home/bigdata/Desktop/k-gnn-master/examples/1-2-3-proteins.py
Launching pytest with arguments /home/bigdata/Desktop/k-gnn-master/examples/1-2-3-proteins.py in /home/bigdata/Desktop/k-gnn-master/examples

============================= test session starts ==============================
platform linux -- Python 3.7.3, pytest-5.0.0, py-1.8.0, pluggy-0.12.0
rootdir: /home/bigdata/Desktop/k-gnn-master, inifile: setup.cfg
plugins: cov-2.7.1
usage: _jb_pytest_runner.py [-h] [--no-train NO_TRAIN]
_jb_pytest_runner.py: error: unrecognized arguments: /home/bigdata/Desktop/k-gnn-master/examples/1-2-3-proteins.py

examples/1-2-3-proteins.py:None (examples/1-2-3-proteins.py)
1-2-3-proteins.py:14: in <module>
    args = parser.parse_args()
../../../anaconda3/envs/ML/lib/python3.7/argparse.py:1752: in parse_args
    self.error(msg % ' '.join(argv))
../../../anaconda3/envs/ML/lib/python3.7/argparse.py:2501: in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
../../../anaconda3/envs/ML/lib/python3.7/argparse.py:2488: in exit
    _sys.exit(status)
E   SystemExit: 2
collected 0 items / 1 errors

**Comment by rusty1s** [comment] 2019-07-05 04:45
How do you start the script? I am wondering why it tries to run `pytest`.

**Comment by AlwaysLightHeart** [comment] 2019-07-05 06:45
I first python setup.py install accodding  to the readme.md ,then I directly run 1-2-3-protiens.py of examples in pycharm. and then the error come out.

**Comment by rusty1s** [comment] 2019-07-05 06:46
I guess PyCharm starts `pytest` instead of `python`. This seems to be a bug on your side.

**Edit:** You can alternatively try to remove the `setup.cfg`. This could fix this issue.

**Comment by AlwaysLightHeart** [comment] 2019-07-05 06:58
Thank you! I run the code in the terminal without previous error.However another error asise.
Downloading https://ls11-www.cs.tu-dortmund.de/people/morris/graphkerneldatasets/PROTEINS.zip
Traceback (most recent call last):
  File "/home/bigdata/anaconda3/envs/ML/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/bigdata/anaconda3/envs/ML/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/bigdata/anaconda3/envs/ML/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/bigdata/anaconda3/envs/ML/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/bigdata/anaconda3/envs/ML/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/home/bigdata/anaconda3/envs/ML/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/home/bigdata/anaconda3/envs/ML/lib/python3.7/http/client.py", line 1384, in connect
    super().connect()
  File "/home/bigdata/anaconda3/envs/ML/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/bigdata/anaconda3/envs/ML/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/home/bigdata/anaconda3/envs/ML/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "1-2-3-proteins.py", line 38, in <module>
    pre_filter=MyFilter())
  File "/home/bigdata/anaconda3/envs/ML/lib/python3.7/site-packages/torch_geometric/datasets/tu_dataset.py", line 56, in __init__
    pre_filter)
  File "/home/bigdata/anaconda3/envs/ML/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 56, in __init__
    pre_filter)
  File "/home/bigdata/anaconda3/envs/ML/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 82, in __init__
    self._download()
  File "/home/bigdata/anaconda3/envs/ML/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 118, in _download
    self.download()
  File "/home/bigdata/anaconda3/envs/ML/lib/python3.7/site-packages/torch_geometric/datasets/tu_dataset.py", line 89, in download
    path = download_url('{}/{}.zip'.format(self.url, self.name), self.root)
  File "/home/bigdata/anaconda3/envs/ML/lib/python3.7/site-packages/torch_geometric/data/download.py", line 23, in download_url
    data = urllib.request.urlopen(url)
  File "/home/bigdata/anaconda3/envs/ML/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/bigdata/anaconda3/envs/ML/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/bigdata/anaconda3/envs/ML/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/home/bigdata/anaconda3/envs/ML/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/bigdata/anaconda3/envs/ML/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/home/bigdata/anaconda3/envs/ML/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

**Comment by rusty1s** [comment] 2019-07-05 07:27
Mh, I do not know why the download doesn't work for you there. You can alternatively download the file manually and extract it to `root_dir/raw`.

**Comment by AlwaysLightHeart** [comment] 2019-07-05 07:36
Thank you again. It is kind of you to help me! I have solved this problem and have run the code successfully!

**Comment by AlwaysLightHeart** [comment] 2019-07-10 01:09
Hello, I want to ask you a question. Could you tell me what is the difference between  1- G N N  N O  T U N I N G and  1- GNN in the code?

**Comment by AlwaysLightHeart** [comment] 2019-07-17 12:58
Hello, I write the code 1-mutag.py of the dataset MUTAG which has not provided refered to the 1-NCI1.py. However, I can not get the result 82.2 showing in the paper. The result is just 70.0 terribly. The code is as following,  and I don't know if the code I write is wrong.

`import os.path as osp

import argparse
import torch
import torch.nn.functional as F
from torch_scatter import scatter_max, scatter_mean
from torch_geometric.datasets import TUDataset
from k_gnn import GraphConv
from torch_geometric.data import DataLoader

parser = argparse.ArgumentParser()
parser.add_argument('--no-train', default=False)
args = parser.parse_args()

BATCH = 32
path = osp.join(osp.dirname(osp.realpath(__file__)), '..', 'data', '1-MUTAG')
dataset = TUDataset(path, name='MUTAG')

perm = torch.randperm(len(dataset), dtype=torch.long)
dataset = dataset[perm]


class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = GraphConv(dataset.num_features, 32)
        self.conv2 = GraphConv(32, 64)
        self.conv3 = GraphConv(64, 64)

        self.fc1 = torch.nn.Linear(64, 64)
        self.fc2 = torch.nn.Linear(64, 32)
        self.fc3 = torch.nn.Linear(32, dataset.num_classes)

    def reset_parameters(self):
        for (name, module) in self._modules.items():
            module.reset_parameters()

    def forward(self, data):
        data.x = F.elu(self.conv1(data.x, data.edge_index))
        data.x = F.elu(self.conv2(data.x, data.edge_index))
        data.x = F.elu(self.conv3(data.x, data.edge_index))

        x_1 = scatter_mean(data.x, data.batch, dim=0)
        x = x_1

        if args.no_train:
            x = x.detach()

        x = F.elu(self.fc1(x))
        x = F.dropout(x, p=0.5, training=self.training)
        x = F.elu(self.fc2(x))
        x = self.fc3(x)
        return F.log_softmax(x, dim=1)


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = Net().to(device)


def train(epoch, loader, optimizer):
    model.train()
    loss_all = 0

    for data in loader:
        data = data.to(device)
        optimizer.zero_grad()
        loss = F.nll_loss(model(data), data.y)
        loss.backward()
        loss_all += data.num_graphs * loss.item()
        optimizer.step()
    return loss_all / len(loader.dataset)


def val(loader):
    model.eval()
    loss_all = 0

    for data in loader:
        data = data.to(device)
        loss_all += F.nll_loss(model(data), data.y, reduction='sum').item()
    return loss_all / len(loader.dataset)


def test(loader):
    model.eval()
    correct = 0

    for data in loader:
        data = data.to(device)
        pred = model(data).max(1)[1]
        correct += pred.eq(data.y).sum().item()
    return correct / len(loader.dataset)


acc = []
for i in range(10):
    model.reset_parameters()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode='min', factor=0.7, patience=5, min_lr=0.00001)

    test_mask = torch.zeros(len(dataset), dtype=torch.uint8)
    n = len(dataset) // 10
    test_mask[i * n:(i + 1) * n] = 1
    test_dataset = dataset[test_mask]
    train_dataset = dataset[1 - test_mask]

    n = len(train_dataset) // 10
    val_mask = torch.zeros(len(train_dataset), dtype=torch.uint8)
    val_mask[i * n:(i + 1) * n] = 1
    val_dataset = train_dataset[val_mask]
    train_dataset = train_dataset[1 - val_mask]

    val_loader = DataLoader(val_dataset, batch_size=BATCH)
    test_loader = DataLoader(test_dataset, batch_size=BATCH)
    train_loader = DataLoader(train_dataset, batch_size=BATCH, shuffle=True)

    print('---------------- Split {} ----------------'.format(i))

    best_val_loss, test_acc = 100, 0
    for epoch in range(1, 101):
        lr = scheduler.optimizer.param_groups[0]['lr']
        train_loss = train(epoch, train_loader, optimizer)
        val_loss = val(val_loader)
        scheduler.step(val_loss)
        if best_val_loss >= val_loss:
            test_acc = test(test_loader)
            best_val_loss = val_loss
        print('Epoch: {:03d}, LR: {:7f}, Train Loss: {:.7f}, '
              'Val Loss: {:.7f}, Test Acc: {:.7f}'.format(
                  epoch, lr, train_loss, val_loss, test_acc))
    acc.append(test_acc)
acc = torch.tensor(acc)
print('---------------- Final Result ----------------')
print('Mean: {:7f}, Std: {:7f}'.format(acc.mean(), acc.std()))`

**Comment by rusty1s** [comment] 2019-07-17 13:16
Yes, you are right. This is something we did not specify in the paper. For `MUTAG`, we actually used `global_add_pool`, so replacing `x_1 = scatter_mean(data.x, data.batch, dim=0)` with `x_1 = scatter_add(data.x, data.batch, dim=0)` yields the correct results.

I reran the experiment and it reports 83.9% accuracy.

**Comment by AlwaysLightHeart** [comment] 2019-07-17 13:22
Thank you! I will try it.

**Comment by AlwaysLightHeart** [comment] 2019-07-17 13:41
em....., I have tried several times,the results are 79.3, 77.8, 77.8,  80.0, 78.3. Each time the highest value even reach 100%,while the lowest value is 44.4. It seems not stable. Can you send all the code to my e-mail(gaojun306@gmail.com)?

**Comment by rusty1s** [comment] 2019-07-17 14:26
Well, it's MUTAG. This dataset is so small that these fluctuations are normal. I added our official `1-mutag.py` example to the `examples/` directory to reproduce the results. Hope that it is now working for you.

**Comment by AlwaysLightHeart** [comment] 2019-07-18 09:09
Thank you, I have run the code 1-mutag.py, getting the result in the paper successfully, even higher. I also write the code 1-2-3-mutag.py and have replaced  scatter_mean(data.x, data.batch, dim=0) with  scatter_add(data.x, data.batch, dim=0) , but it can not reach the result 86.1 in the paper, getting 82.2.  I want to know if  86.1 is the best result or the stable result.  I think it should be caused by the MyFilter and MyPreTransform.  my code is as following, hoping you can point out my mistake. Thank you again!

`import os.path as osp

import argparse
import torch
import torch.nn.functional as F
from torch_scatter import scatter_mean, scatter_add
from torch_geometric.datasets import TUDataset
import torch_geometric.transforms as T
from k_gnn import DataLoader, GraphConv, avg_pool
from k_gnn import TwoMalkin, ConnectedThreeMalkin

parser = argparse.ArgumentParser()
parser.add_argument('--no-train', default=False)
args = parser.parse_args()


class MyFilter(object):
    def __call__(self, data):
        return True


BATCH = 20
path = osp.join(
    osp.dirname(osp.realpath(__file__)), '..', 'data', '1-2-3-MUTAG')
dataset = TUDataset(
    path,
    name='MUTAG',
    pre_transform=T.Compose(
        [TwoMalkin(), ConnectedThreeMalkin()]),
    pre_filter=MyFilter())

perm = torch.randperm(len(dataset), dtype=torch.long)
dataset = dataset[perm]

dataset.data.iso_type_2 = torch.unique(dataset.data.iso_type_2, True, True)[1]
num_i_2 = dataset.data.iso_type_2.max().item() + 1
dataset.data.iso_type_2 = F.one_hot(
    dataset.data.iso_type_2, num_classes=num_i_2).to(torch.float)

dataset.data.iso_type_3 = torch.unique(dataset.data.iso_type_3, True, True)[1]
num_i_3 = dataset.data.iso_type_3.max().item() + 1
dataset.data.iso_type_3 = F.one_hot(
    dataset.data.iso_type_3, num_classes=num_i_3).to(torch.float)


class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = GraphConv(dataset.num_features, 32)
        self.conv2 = GraphConv(32, 64)
        self.conv3 = GraphConv(64, 64)
        self.conv4 = GraphConv(64 + num_i_2, 64)
        self.conv5 = GraphConv(64, 64)
        self.conv6 = GraphConv(64 + num_i_3, 64)
        self.conv7 = GraphConv(64, 64)
        self.fc1 = torch.nn.Linear(6 * 64, 64)
        self.fc2 = torch.nn.Linear(64, 32)
        self.fc3 = torch.nn.Linear(32, dataset.num_classes)

    def reset_parameters(self):
        for (name, module) in self._modules.items():
            module.reset_parameters()

    def forward(self, data):
        data.x = F.elu(self.conv1(data.x, data.edge_index))
        data.x = F.elu(self.conv2(data.x, data.edge_index))
        data.x = F.elu(self.conv3(data.x, data.edge_index))
        x = data.x
        x_1 = scatter_add(data.x, data.batch, dim=0)

        data.x = avg_pool(x, data.assignment_index_2)
        data.x = torch.cat([data.x, data.iso_type_2], dim=1)

        data.x = F.elu(self.conv4(data.x, data.edge_index_2))
        data.x = F.elu(self.conv5(data.x, data.edge_index_2))
        x_2 = scatter_add(data.x, data.batch_2, dim=0)

        data.x = avg_pool(x, data.assignment_index_3)
        data.x = torch.cat([data.x, data.iso_type_3], dim=1)

        data.x = F.elu(self.conv6(data.x, data.edge_index_3))
        data.x = F.elu(self.conv7(data.x, data.edge_index_3))
        x_3 = scatter_add(data.x, data.batch_3, dim=0)

        x = torch.cat([x_1, x_2, x_3], dim=1)

        if args.no_train:
            x = x.detach()

        x = F.elu(self.fc1(x))
        x = F.dropout(x, p=0.5, training=self.training)
        x = F.elu(self.fc2(x))
        x = self.fc3(x)
        return F.log_softmax(x, dim=1)


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = Net().to(device)


def train(epoch, loader, optimizer):
    model.train()
    loss_all = 0

    for data in loader:
        data = data.to(device)
        optimizer.zero_grad()
        loss = F.nll_loss(model(data), data.y)
        loss.backward()
        loss_all += data.num_graphs * loss.item()
        optimizer.step()
    return loss_all / len(loader.dataset)


def val(loader):
    model.eval()
    loss_all = 0

    for data in loader:
        data = data.to(device)
        loss_all += F.nll_loss(model(data), data.y, reduction='sum').item()
    return loss_all / len(loader.dataset)


def test(loader):
    model.eval()
    correct = 0

    for data in loader:
        data = data.to(device)
        pred = model(data).max(1)[1]
        correct += pred.eq(data.y).sum().item()
    return correct / len(loader.dataset)


acc = []
for i in range(10):
    model.reset_parameters()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode='min', factor=0.7, patience=5, min_lr=0.00001)

    test_mask = torch.zeros(len(dataset), dtype=torch.uint8)
    n = len(dataset) // 10
    test_mask[i * n:(i + 1) * n] = 1
    test_dataset = dataset[test_mask]
    train_dataset = dataset[1 - test_mask]

    n = len(train_dataset) // 10
    val_mask = torch.zeros(len(train_dataset), dtype=torch.uint8)
    val_mask[i * n:(i + 1) * n] = 1
    val_dataset = train_dataset[val_mask]
    train_dataset = train_dataset[1 - val_mask]

    val_loader = DataLoader(val_dataset, batch_size=BATCH)
    test_loader = DataLoader(test_dataset, batch_size=BATCH)
    train_loader = DataLoader(train_dataset, batch_size=BATCH, shuffle=True)

    print('---------------- Split {} ----------------'.format(i))

    best_val_loss, test_acc = 100, 0
    for epoch in range(1, 101):
        lr = scheduler.optimizer.param_groups[0]['lr']
        train_loss = train(epoch, train_loader, optimizer)
        val_loss = val(val_loader)
        scheduler.step(val_loss)
        if best_val_loss >= val_loss:
            test_acc = test(test_loader)
            best_val_loss = val_loss
        print('Epoch: {:03d}, LR: {:7f}, Train Loss: {:.7f}, '
              'Val Loss: {:.7f}, Test Acc: {:.7f}'.format(
                  epoch, lr, train_loss, val_loss, test_acc))
    acc.append(test_acc)
acc = torch.tensor(acc)
print('---------------- Final Result ----------------')
print('Mean: {:7f}, Std: {:7f}'.format(acc.mean(), acc.std()))`

**Comment by AlwaysLightHeart** [comment] 2019-07-18 13:52
Excuse me! I have another trouble in the code 1-2-3-PTC_FM.py refering the code of 1-2-3-mutag.py which can run successfully. However, there is an error as following. It says that error happened in the line
`N_3 = data.assignment_index_3[1].max().item() + 1` in dataloader.py.  I am so confused that why there are not such error when running another two dataset of 1-2-3-proteins and 1-2-3-mutag.
Traceback (most recent call last):
  File "1-2-3-PTC_FM.py", line 167, in <module>
    train_loss = train(epoch, train_loader, optimizer)
  File "1-2-3-PTC_FM.py", line 108, in train
    for data in loader:
  File "/home/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 560, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/lib/python3.7/site-packages/k_gnn-0.0.0-py3.7-linux-x86_64.egg/k_gnn/dataloader.py", line 44, in collate
    N_3 = data.assignment_index_3[1].max().item() + 1
RuntimeError: invalid argument 1: tensor must have one dimension at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:592

**Comment by AlwaysLightHeart** [comment] 2019-07-18 13:57
Excuse me! I have another trouble in the code 1-2-3-PTC_FM.py、1-2-3-NCI1.py ，refering the code of 1-2-3-mutag.py  which can be run successfully. However, they both have an error as following. It says that error happened in the line `N_3= data.assignment_index_3[1].max().item() + 1` in dataloader.py.  I am so confused that why there are not such error when running another two dataset of 1-2-3-proteins and 1-2-3-mutag.

Traceback (most recent call last):
File "1-2-3-PTC_FM.py", line 167, in 
train_loss = train(epoch, train_loader, optimizer)
File "1-2-3-PTC_FM.py", line 108, in train
for data in loader:
File "/home/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 560, in next
batch = self.collate_fn([self.dataset[i] for i in indices])
File "/home/lib/python3.7/site-packages/k_gnn-0.0.0-py3.7-linux-x86_64.egg/k_gnn/dataloader.py", line 44, in collate
N_3 = data.assignment_index_3[1].max().item() + 1
RuntimeError: invalid argument 1: tensor must have one dimension at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:592

**Comment by rusty1s** [comment] 2019-07-18 14:04
Hi, I will upload the `1-2-3-mutag.py` script soon. Concerning your other problem: In case the graph is really small, the 3-tuple graph can be empty. We filter those trouble-some graphs out, as our approach is kinda useless on those small graphs with only 3 to 5 nodes anyway.

**Comment by AlwaysLightHeart** [comment] 2019-07-18 14:18
Thank you very much! I will try it.

**Comment by AlwaysLightHeart** [comment] 2019-07-19 07:42
Hello! I modified the 1-2-3-PTC_FM.py and 1-2-3-NCI1.py by  adding the filtering condition to filter trouble-some graphs out.  In 1-2-3-PTC_FM.py , I filtered out graphs with number of nodes less than 10 and the code can run successfully!  I also tried to run the code 1-2-NCI1.py successfully by filtering out graphs with number of node less than 5.  However, in 1-2-3-NCI1.py, I failed to run it.  I even filtered out graphs with number of nodes less than 20, it  still showed the error happened in N_3= data.assignment_index_3[1].max().item() + 1 in dataloader.py.  Could you tell me what's your graph's filtering condition of number of nodes in 1-2-3-NCI1.py and 1-2-3-PTC_FM.py.

**Comment by rusty1s** [comment] 2019-07-19 07:46
Sure, and sorry for the inconveniences. We use
```python
class MyFilter(object):
    def __call__(self, data):
        return data.num_nodes >= 5
```
in `1-2-3-ptc.py` and
```python
transform = T.Compose([MyPreTransform(), TwoMalkin(), ConnectedThreeMalkin()])


class MyFilter(object):
    def __call__(self, data):
        try:
            data = transform(data)
            return True
        except RuntimeError:
            return False
```
in `1-2-3-nci.py`.

**Comment by rusty1s** [comment] 2019-07-19 07:55
It seems that this strategy is no longer working in PyTorch 1.1 (in 0.4.1 it would raise an error once it encounters a 0-element tensor). I need to look into it.

**Comment by rusty1s** [comment] 2019-07-19 07:58
```python
transform = T.Compose([MyPreTransform(), TwoMalkin(), ConnectedThreeMalkin()])


class MyFilter(object):
    def __call__(self, data):
        data = transform(data)
        return data.assignment_index_2.numel() > 0 and data.assignment_index_3.numel() > 0
```
works for me :)

**Comment by AlwaysLightHeart** [comment] 2019-07-19 08:19
It really works. Thank you for your help and  guidance patiently !

**Comment by AlwaysLightHeart** [comment] 2019-07-20 10:21
Hi, I have another question. What's the differnce between '1-2-3- G N N N O T U N I N G' and '1-2-3-GNN'?  Is it that '1-2-3- G N N N O T U N I N G' means the average result of the dataset and  '1-2-3-GNN' means the highest result? Beacuse for some small datasets, it seems not very stable. Have a nice weekend.

**Comment by rusty1s** [comment] 2019-07-20 10:36
No, it means that we do not learn the parameters of the graph convolution, just the parameters of the final MLP classifier.

**Comment by AlwaysLightHeart** [comment] 2019-07-21 06:09
OK, I got it. Thank you again!
